name: BackpackPlus
main: com.nexussphere.backpackplus.CrossServerBackpack
version: 1.0.45-MC1.21
api-version: "1.21"
authors: [NS_DracoMC]
description: Plugin balo nâng cao, đồng bộ và tùy chỉnh.
website: https://vietrealm.com/
softdepend: [Vault, PlayerPoints, ProtocolLib]
commands:
  backpack:
    description: Lệnh quản lý balo.
    usage: /backpack <lệnh_con> [tham_số...]
    aliases: [bplus, bp]
permissions:
  backpackplus.admin.revoke:
    description: Vô hiệu hóa và xóa các bản sao balo bị dupe.
    default: op
  backpackplus.admin.refundskin:
    description: Thu hồi skin và hoàn lại điểm cho người chơi.
    default: op
  backpackplus.command.skins:
    description: Cho phép người chơi mở cửa hàng skin ba lô.
    default: op
  backpackplus.command.wardrobe:
    description: Cho phép người chơi mở tủ đồ skin của họ.
    default: op
  backpackplus.create:
    description: Cho phép tạo balo vật lý theo số trang.
    default: op
  backpackplus.admin.open:
    description: Cho phép mở balo của người khác.
    default: op
  backpackplus.admin.give:
    description: Cho phép admin give lại ba lô cho người chơi.
    default: op
  backpackplus.admin.forcelost:
    description: Cho phép admin đánh dấu balo của người khác là bị mất.
    default: op
  backpackplus.admin.delete:
    description: Cho phép xóa vĩnh viễn một ba lô của người chơi.
    default: op
  backpackplus.command.upgrade:
    description: Cho phép nâng cấp số slot của balo đang cầm trên tay.
    default: op
  backpackplus.command.rename:
    description: Cho phép đổi tên ba lô đang cầm trên tay.
    default: op
  backpackplus.command.transfer:
    description: Cho phép chuyển quyền sở hữu ba lô cho người khác.
    default: op
  backpackplus.reload:
    description: Cho phép tải lại cấu hình của plugin.
    default: op
  backpackplus.recover:
    description: Cho phép người chơi lấy lại balo đã mất của chính mình.
    default: op
  backpackplus.admin.recover:
    description: Cho phép lấy lại balo đã mất của người chơi khác.
    default: op
  backpackplus.command.trust:
    description: Cho phép người chơi tin cậy người khác sử dụng ba lô.
    default: op
  backpackplus.command.untrust:
    description: Cho phép người chơi hủy tin cậy người khác sử dụng ba lô.
    default: op
  backpackplus.command.trustlist:
    description: Cho phép người chơi xem danh sách tin cậy của ba lô.
    default: op
  backpackplus.command.buy:
    description: Cho phép người chơi mua ba lô bằng điểm.
    default: op
  backpackplus.admin.buy:
    description: Cho phép admin mua ba lô cho người chơi khác.
    default: op
  backpackplus.command.buyup:
    description: Cho phép người chơi nâng cấp ba lô bằng điểm.
    default: op
  backpackplus.admin.buyup:
    description: Cho phép admin nâng cấp ba lô cho người chơi khác.
    default: op